---
- name: Install Docker
  tags: install
  block:
    - name: Install Docker | Install packages to allow apt to use a repository over HTTPS
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add Docker apt key.
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'
        force: true

    - name: Add Docker repository.
      ansible.legacy.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true

    - name: Prefix the Docker package version with the correct separator on RedHat.
      ansible.builtin.set_fact:
        _docker_package_version: "={{ docker_package_version }}"
      when: docker_package_version is defined

    - name: Install Docker | Install Docker engine
      ansible.builtin.apt:
        name:
          - "docker-ce{{ _docker_package_version | default('') }}"
          - "docker-ce-cli{{ _docker_package_version | default('') }}"
          - containerd.io
        update_cache: true
        state: present
      notify: start docker
    
    - name: Install Docker | Install Docker plugins
      ansible.builtin.apt:
        name:
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true
      notify: start docker
