---
- name: Debian.yaml | Install Docker
  tags: install
  block:
    - name: Debian.yaml | Install packages to allow apt to use a repository over HTTPS
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Debian.yaml | Add Docker apt key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'
        force: true

    - name: Debian.yaml | Add Docker repository
      ansible.legacy.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true

    - name: Debian.yaml | Check Docker package
      ansible.builtin.include_tasks: version.yaml
      when: docker_version is defined

    - name: Debian.yaml | Install Docker engine
      ansible.builtin.apt:
        name:
          - "docker-ce{{ _docker_ce_version | default('') }}"
          - "docker-ce-cli{{ _docker_package_version | default('') }}"
          - containerd.io
        update_cache: true
        state: present
      when: _docker_need_update is not defined
      notify: start docker

    - name: Debian.yaml | Update Docker
      ansible.builtin.shell: "apt-get install -y docker-ce{{ _docker_ce_version }} docker-ce-cli{{ _docker_ce_cli_version }} containerd.io"
      when: 
        - _docker_need_update is defined
      register: upgrade
      changed_when: "'Nothing to do' not in upgrade"
      notify: restart docker
    
    - name: Debian.yaml | Install Docker plugins
      ansible.builtin.apt:
        name:
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true
      notify: start docker
