---
- name: Install Docker | Preparation before installing
  include_tasks: "{{ ansible_facts['os_family'] }}.yml"

- name: Install Docker | Install Docker engine
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- block:
  - name: Install Docker | Make sure the Docker daemon configuration directory exists.
    ansible.builtin.file:
      path: /etc/docker
      owner: root
      group: root
      mode: 0755
      state: directory

  - name: Install Docker | Create docker configuration file daemon.json
    ansible.builtin.template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: '0644'
  when: docker_daemon_config is defined
  notify: restart docker

- name: Install Docker | Create Docker data directory
  ansible.builtin.file:
    path: "{{ docker_daemon_config['data-root'] }}"
    owner: root
    group: root
    mode: 0750
    state: directory
  when: docker_daemon_config['data-root'] is defined

- name: Install Docker | Enable and start service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
