---
- name: Include OS specific vars
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yaml"

- name: Install Docker
  ansible.builtin.import_tasks: docker.yaml

- name: Setup Docker Swarm
  ansible.builtin.import_tasks: swarm.yaml
  tags:
    - swarm
