---
- block:
    - name: Preparation before installing
      include_tasks: "{{ ansible_facts['os_family'] }}.yml"

    - name: Docker | Install Docker engine
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Docker | Enable and start service
      service:
        name: docker
        state: started
        enabled: true
    
    - name: Docker | Create docker configuration file daemon.json
      ansible.builtin.template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'
      when: docker_daemon_config is defined
  tags:
    - docker

- block:
    - name: Init Docker Swarm
      import_tasks: compose.yml
  tags:
    - compose

- block:
    - name: Setup Docker Swarm
      import_tasks: swarm.yml
  tags:
    - swarm
