---
- name: Install the yum-utils package
  ansible.builtin.package:
    name: yum-utils
    state: present

- name: Add Docker repository (.rpm)
  shell:
    cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  changed_when: false
