---
- name: Install Docker
  tags: install
  block:
    - name: Install Docker | Install the yum-utils package
      ansible.builtin.package:
        name: yum-utils
        state: present

    - name: Install Docker | Add Docker repository (.rpm)
      ansible.builtin.shell:
        cmd: yum-config-manager --add-repo {{ docker_repo_url }}
      changed_when: false

    - name: Check docker version
      ansible.builtin.include_tasks: version.yaml
      when: docker_version is defined

    - name: Install Docker | Install Docker
      ansible.builtin.dnf:
        name:
          - "docker-ce{{ _docker_ce_version | default('') }}"
          - "docker-ce-cli{{ _docker_ce_cli_version | default('') }}"
          - containerd.io 
        state: present
      notify: start docker
    
    - name: Install Docker | Install Docker plugins
      ansible.builtin.dnf:
        name:
          - docker-buildx-plugin 
          - docker-compose-plugin
        state: present
