---
- name: Check swarm node
  ansible.builtin.shell:
    cmd: docker info
  ignore_errors: true
  changed_when: false
  register: swarm_check
  check_mode: false

- name: Init Swarm
  when:
    - inventory_hostname == manager_hosts[0]
  block:
    - name: Initialize a swarm
      ansible.builtin.command: docker swarm init --advertise-addr {{ advertise_addr }}
      when:
        - "swarm_check.stdout is search('Swarm: inactive')"

    - name: Get join tokens
      ansible.builtin.command: "docker swarm join-token {{ item }}"
      with_items:
        - manager
        - worker
      register: join_tokens
      changed_when: False

- name: Join members
  when:
    - "swarm_check.stdout is search('Swarm: inactive')"
    - inventory_hostname != manager_hosts[0]
  block:
    - name: Join manager node to the cluster
      ansible.builtin.shell:
        cmd: "{{ (hostvars[manager_hosts[0]].join_tokens.results[0].stdout_lines | map('trim'))[-1] }}"
      when:
        - swarm_role == "manager"

    - name: Join woker node to the cluster
      ansible.builtin.shell:
        cmd: "{{ (hostvars[manager_hosts[0]].join_tokens.results[1].stdout_lines | map('trim'))[-1] }}"
      when:
        - swarm_role == "worker"
