---
- name: version.yaml | Get packages version
  ansible.builtin.shell: "{{ show_version_cmd }}"
  register: docker_package_version
  changed_when: false
  failed_when: false
  with_items:
    - docker-ce
    - docker-ce-cli

- name: version.yaml | Set docker-ce version.
  ansible.builtin.set_fact:
    _docker_ce_version: "{{ version_delimiter }}{{ docker_package_version.results[0].stdout }}"
  when: docker_package_version is defined

- name: version.yaml | Set docker-ce-cli version.
  ansible.builtin.set_fact:
    _docker_ce_cli_version: "{{ version_delimiter }}{{ docker_package_version.results[1].stdout }}"
  when: docker_package_version is defined