Vagrant.configure("2") do |config|
    servers = ["swarm01", "swarm02", "swarm03"]
    servers.each_with_index do |server, index|
        config.vm.define "#{server}" do |d|
            d.vm.box = "centos/8"
            d.vm.network "private_network", ip: "10.0.3.3#{index+1}", name: "vboxnet1"
            d.vm.hostname = "#{server}"
            d.vm.disk :disk, size: "10GB", primary: true
            d.vm.provider "virtualbox" do |vb|
                vb.memory = 2048
                vb.cpus = 1
                vb.customize ["modifyvm", :id, "--audiocontroller", "sb16"]
                vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
            end
            d.vm.provision "file", source: "./key.pub", destination: "/home/vagrant/key.pub"
            d.vm.provision "shell", inline: <<-SHELL
                cat /home/vagrant/key.pub >> /home/vagrant/.ssh/authorized_keys
            SHELL
        end
    end
end