---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance01
    image: ${MOLECULE_PLATFORM_IMAGE:-"artemshestakov/almalinux-8-docker:latest"}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: instance02
    image: ${MOLECULE_PLATFORM_IMAGE:-"artemshestakov/almalinux-8-docker:latest"}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: instance03
    image: ${MOLECULE_PLATFORM_IMAGE:-"artemshestakov/almalinux-8-docker:latest"}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    hosts:
      managers:
        hosts:
          instance01:
            swarm_role: manager
      workers:
        hosts:
          instance02:
          instance03:
        vars:
          swarm_role: worker
verifier:
  name: ansible
