---
- name: Prepare instance
  hosts: all
  tasks:
    - name: Create a directory /docker
      ansible.builtin.file:
        path: /docker
        state: directory
        mode: '0755'
      tags: docker